## Combine all South East Asian Features into one Dataframe

In [2]:
import pandas as pd

In [3]:
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns

In [4]:
tobacco_use_ww = pd.read_csv("Data/tobacco_use_ww.csv") # done | j | hm

In [5]:
tobbacco_production = pd.read_csv("Data/tobacco_production.csv") # done

In [6]:
stop_smoking = pd.read_csv("Data/stop_smoking.csv") # done || j | hm | p

In [7]:
sales_per_day = pd.read_csv("Data/sales_per_day.csv") # done || j | hm | p

In [8]:
death_rates_smoking_age = pd.read_csv("Data/death_rates_smoking_age.csv")# done || j hm | p

In [9]:
SEA_Countries = tobacco_use_ww[tobacco_use_ww["ParentLocation"]=="South-East Asia"]["Location"].unique()[1:]

In [10]:
SEA_Countries_Code = tobacco_use_ww[tobacco_use_ww["ParentLocation"]=="South-East Asia"]["SpatialDimValueCode"].unique()[1:]

In [11]:
drsmaDict = dict(pd.read_csv("Data/death_rates_smoking_age.csv")[["Entity","Code"]].values)

In [12]:
spdDict = dict(pd.read_csv("Data/sales_per_day.csv")[["Entity","Code"]].values)

In [13]:
ssDict = dict(pd.read_csv("Data/stop_smoking.csv")[["Entity","Code"]].values)

In [14]:
tuDict = dict(pd.read_csv("Data/tobacco_use_ww.csv")[["Location","SpatialDimValueCode"]].values)

In [15]:
drsmaDict.update(spdDict)
drsmaDict.update(ssDict)
drsmaDict.update(tuDict)

In [16]:
len(drsmaDict)

254

## Tobacco use

In [17]:
#SEAtobacco_use = tobacco_use_ww[tobacco_use_ww["ParentLocation"]=="South-East Asia"]

In [18]:
tobacco_useP = tobacco_use_ww.rename({"SpatialDimValueCode":"Code"},axis=1)[["Code","Year","Gender","Value"]]

In [19]:
tobacco_useP = tobacco_useP.pivot_table("Value",["Code"],["Year","Gender"])

In [20]:
tobacco_useP.columns = [x[1]+"_"+str(x[0]) for x in tobacco_useP.columns]

In [21]:
tobacco_useP

,Both sexes_2000,Female_2000,Male_2000,Both sexes_2005,Female_2005,Male_2005,Both sexes_2010,Female_2010,Male_2010,Both sexes_2013,...,Male_2015,Both sexes_2016,Female_2016,Male_2016,Both sexes_2017,Female_2017,Male_2017,Both sexes_2018,Female_2018,Male_2018
Code,,,,,,,,,,,,,,,,,,,,,
ALB,34.2,11.1,57.4,32.7,10.0,55.3,31.1,9.1,53.2,30.3,...,51.4,29.7,8.2,51.1,29.3,8.0,50.6,29.2,7.9,50.5
AND,36.3,29.9,42.6,35.4,29.6,41.2,34.7,29.5,39.9,34.3,...,38.8,33.9,29.4,38.4,33.9,29.4,38.4,33.8,29.5,38.1
ARE,21.8,1.3,42.3,20.6,1.1,40.0,19.4,1.0,37.9,19.0,...,36.5,18.5,0.8,36.1,18.5,0.8,36.1,18.2,0.8,35.6
ARG,46.2,39.0,53.5,37.1,29.7,44.6,30.1,22.9,37.2,26.6,...,31.3,23.6,17.0,30.2,22.7,16.2,29.2,21.8,15.4,28.2
ARM,34.3,2.6,66.1,32.3,2.2,62.4,30.0,1.9,58.2,28.9,...,54.1,27.5,1.6,53.5,27.3,1.6,52.9,26.7,1.6,51.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WSM,41.3,24.1,58.5,37.2,21.8,52.5,33.5,19.7,47.4,31.6,...,43.0,29.9,17.5,42.2,29.3,17.2,41.5,28.9,16.9,40.8
YEM,30.9,17.5,44.2,27.4,14.6,40.2,24.5,12.2,36.9,23.0,...,34.0,21.7,9.9,33.5,21.3,9.6,33.0,20.9,9.3,32.5
ZAF,38.1,28.9,47.3,35.8,24.6,47.0,33.9,20.9,46.9,32.8,...,46.7,32.0,17.2,46.9,31.6,16.6,46.5,31.4,16.0,46.8
ZMB,19.9,7.9,31.9,18.2,6.7,29.7,16.7,5.6,27.8,15.9,...,26.1,15.2,4.6,25.7,14.9,4.5,25.4,14.7,4.4,25.0
ZWE,18.3,2.9,33.7,17.0,2.3,31.6,15.6,1.9,29.4,14.9,...,27.5,14.3,1.4,27.2,14.1,1.4,26.9,13.9,1.3,26.5

## tobbacco_production

In [22]:
((_,metricTons),(_,MilUsd)) = list(tobbacco_production.drop("Value Footnotes",axis=1).groupby("Unit"))

In [23]:
metricTons = metricTons.pivot_table("Value",["Country or Area"],["Year"])

In [24]:
MilUsd = MilUsd.pivot_table("Value",["Country or Area"],["Year"])

In [25]:
drsmaDict.update({"China, Macao Special Administrative Region":"MAC",
                  "The former Yugoslav Republic of Macedonia":"MKD",
                   "Cabo Verde":"CPV",
                   "Syrian Arab Republic":"SYR",
                   "Viet Nam":"VNM"})

In [26]:
MilUsd = MilUsd.reset_index()

MilUsd["Code"] = MilUsd["Country or Area"].apply(lambda x: drsmaDict[x])

In [27]:
MilUsd = MilUsd.drop("Country or Area",axis=1).set_index("Code")

In [28]:
MilUsd.head()

Year,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Code,,,,,,,,,,,,,,,,,,,,,
ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.517025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
AZE,NaN,NaN,NaN,NaN,NaN,3.240836,5.798243,1.697244,1.527268,1.933458,...,1.048800,2.799349,3.732349,6.104810,8.737646,6.491478,7.137931,9.817077,6.929778,7.457441
BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.469845,NaN,5.349070
BRA,NaN,NaN,NaN,NaN,NaN,2.475959,14.444471,1.262481,1.019495,4.268069,...,51.457204,77.499482,57.614741,55.702043,70.476139,70.444313,74.455796,90.393659,98.170738,NaN

In [29]:
MilUsd.columns = ["MilUsd_"+str(x) for x in MilUsd.columns]

In [30]:
MilUsd.head()

,MilUsd_1995,MilUsd_1996,MilUsd_1997,MilUsd_1998,MilUsd_1999,MilUsd_2000,MilUsd_2001,MilUsd_2002,MilUsd_2003,MilUsd_2004,...,MilUsd_2007,MilUsd_2008,MilUsd_2009,MilUsd_2010,MilUsd_2011,MilUsd_2012,MilUsd_2013,MilUsd_2014,MilUsd_2015,MilUsd_2016
Code,,,,,,,,,,,,,,,,,,,,,
ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.517025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
AZE,NaN,NaN,NaN,NaN,NaN,3.240836,5.798243,1.697244,1.527268,1.933458,...,1.048800,2.799349,3.732349,6.104810,8.737646,6.491478,7.137931,9.817077,6.929778,7.457441
BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.469845,NaN,5.349070
BRA,NaN,NaN,NaN,NaN,NaN,2.475959,14.444471,1.262481,1.019495,4.268069,...,51.457204,77.499482,57.614741,55.702043,70.476139,70.444313,74.455796,90.393659,98.170738,NaN

In [31]:
metricTons = metricTons.reset_index()

In [32]:
metricTons["Code"] = metricTons["Country or Area"].apply(lambda x: drsmaDict[x])

In [33]:
metricTons = metricTons.drop("Country or Area",axis=1).set_index("Code")

In [34]:
#metricTons.drop("index",axis=1,inplace=True)

In [35]:
metricTons.columns = ["metricTons_"+str(x) for x in metricTons.columns]

In [36]:
metricTons.head()

,metricTons_1995,metricTons_1996,metricTons_1997,metricTons_1998,metricTons_1999,metricTons_2000,metricTons_2001,metricTons_2002,metricTons_2003,metricTons_2004,...,metricTons_2007,metricTons_2008,metricTons_2009,metricTons_2010,metricTons_2011,metricTons_2012,metricTons_2013,metricTons_2014,metricTons_2015,metricTons_2016
Code,,,,,,,,,,,,,,,,,,,,,
ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,751.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DZA,7803.6,8307.1,8382.3,8497.5,8326.0,8145.8,7063.2,7099.6,7153.4,6976.0,...,7734.0,7103.0,8068.0,8273.0,8612.0,8130.0,8241.0,7648.0,7483.0,NaN
AUS,23083.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
AZE,13585.0,8539.0,10134.0,5317.0,7761.0,5869.0,8622.0,4030.0,2293.0,2548.0,...,1038.8,1479.2,1543.0,2027.0,2558.7,1963.6,2112.0,2430.2,1691.5,1946.9

## stop smoking

In [37]:
stop_smoking = stop_smoking.drop("Entity",axis=1).pivot_table(["AvgCigarettePriceDollars","AvgTaxesAsPctCigarettePrice","EnforceBansTobaccoAd","HelpToQuit"],
                                                                                             "Code","Year")

In [38]:
stop_smoking

     AvgCigarettePriceDollars       AvgTaxesAsPctCigarettePrice        \
Year                     2012  2014                        2012  2014
Code
AFG                       NaN   NaN                         NaN   NaN
AGO                       NaN   NaN                         NaN   NaN
ALB                       NaN   NaN                         NaN   NaN
AND                       NaN   NaN                         NaN   NaN
ARE                      1.55  1.82                        24.5  21.1
...                       ...   ...                         ...   ...
WSM                      5.96   NaN                        59.5   NaN
YEM                      1.71  1.94                        52.9  53.7
ZAF                      5.16  5.48                        47.6  48.1
ZMB                      1.68  1.81                        25.8  21.3
ZWE                      0.67  1.07                        57.6  59.8

     EnforceBansTobaccoAd                HelpToQuit
Year                 2007 2010 2012 2014       2007 2010 2012 2014
Code
AFG                   4.0  4.0  4.0  4.0        3.0  3.0  3.0  3.0
AGO                   2.0  2.0  2.0  2.0        3.0  3.0  3.0  3.0
ALB                   5.0  5.0  5.0  5.0        2.0  3.0  4.0  4.0
AND                   2.0  2.0  2.0  2.0        4.0  4.0  4.0  4.0
ARE                   4.0  4.0  4.0  5.0        3.0  5.0  5.0  5.0
...                   ...  ...  ...  ...        ...  ...  ...  ...
WSM                   2.0  4.0  4.0  4.0        3.0  3.0  3.0  3.0
YEM                   4.0  4.0  4.0  5.0        3.0  3.0  3.0  3.0
ZAF                   4.0  4.0  4.0  4.0        3.0  3.0  3.0  4.0
ZMB                   2.0  2.0  2.0  2.0        3.0  3.0  3.0  3.0
ZWE                   2.0  2.0  2.0  2.0        3.0  3.0  3.0  3.0

[194 rows x 12 columns]

In [39]:
stop_smoking.columns = [x[0]+"_"+str(x[1]) for x in stop_smoking.columns]

## Sales Per Day

In [40]:
sales_per_day["Code"].unique()

array(['ARM', 'AUS', 'AUT', 'AZE', 'BLR', 'BEL', 'BGR', 'CAN', 'HRV',
       'CZE', 'OWID_CZS', 'DNK', 'EST', 'FIN', 'FRA', 'GEO', 'DEU', 'GRC',
       'HUN', 'ISL', 'IRL', 'ISR', 'ITA', 'JPN', 'KAZ', 'KGZ', 'LVA',
       'LTU', 'MDA', 'NLD', 'NZL', 'NOR', 'POL', 'PRT', 'ROU', 'RUS',
       'SVK', 'SVN', 'ESP', 'SWE', 'CHE', nan, 'GBR', 'USA', 'OWID_YGS'],
      dtype=object)

In [41]:
sales_per_day

          Entity      Code  Year   amt
0        Armenia       ARM  1988  12.0
1        Armenia       ARM  1989  11.6
2        Armenia       ARM  1990  11.9
3        Armenia       ARM  1991   9.3
4        Armenia       ARM  1992   4.9
...          ...       ...   ...   ...
2762  Yugoslavia  OWID_YGS  1988   8.9
2763  Yugoslavia  OWID_YGS  1989   8.5
2764  Yugoslavia  OWID_YGS  1990   8.5
2765  Yugoslavia  OWID_YGS  1991   7.8
2766  Yugoslavia  OWID_YGS  1992   6.7

[2767 rows x 4 columns]

In [42]:
sales_per_day = sales_per_day.drop("Entity",axis=1).pivot_table("amt","Code","Year")

In [43]:
sales_per_day.columns

Int64Index([1875, 1880, 1885, 1890, 1895, 1900, 1901, 1902, 1903, 1904,
            ...
            2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015],
           dtype='int64', name='Year', length=121)

In [44]:
sales_per_day.columns = ["sales_per_day_"+str(x) for x in sales_per_day.columns]

In [45]:
sales_per_day

,sales_per_day_1875,sales_per_day_1880,sales_per_day_1885,sales_per_day_1890,sales_per_day_1895,sales_per_day_1900,sales_per_day_1901,sales_per_day_1902,sales_per_day_1903,sales_per_day_1904,...,sales_per_day_2006,sales_per_day_2007,sales_per_day_2008,sales_per_day_2009,sales_per_day_2010,sales_per_day_2011,sales_per_day_2012,sales_per_day_2013,sales_per_day_2014,sales_per_day_2015
Code,,,,,,,,,,,,,,,,,,,,,
ARM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.1,4.1,4.2,4.1,4.0,NaN,NaN,NaN,NaN,NaN
AUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.8,6.0,5.5,5.7,6.3,5.2,NaN,NaN,NaN,NaN
BGR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.1,8.8,8.3,6.6,5.7,5.8,6.0,5.9,NaN
BLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.4,3.2,3.0,3.1,3.5,NaN,NaN,NaN,NaN,NaN
CHE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.8,5.4,5.7,5.6,NaN,NaN,NaN,NaN,NaN,NaN
CZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.4,6.7,6.3,6.0,5.5,5.1,5.3,4.1,4.4,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.5,4.4,4.2,4.3,4.2,4.4,4.2,4.1,4.1,4.2
DNK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,5.6,5.5,5.5,5.4,NaN,NaN,NaN,NaN,NaN
ESP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.8,6.6,6.7,6.1,5.5,NaN,NaN,NaN,NaN,NaN
EST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.2,5.3,5.1,5.1,4.8,4.6,4.7,4.5,4.5,NaN
FIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,3.9,5.1,2.9,NaN,NaN,NaN,NaN,NaN,NaN
FRA,0.1,0.1,0.1,0.1,0.1,0.2,0.2,0.2,0.2,0.2,...,3.5,3.5,3.4,3.5,3.5,NaN,NaN,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.9,4.7,4.5,4.3,4.0,3.5,3.4,3.2,3.0,NaN
GEO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GRC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.1,10.6,9.1,10.4,7.6,8.3,7.0,NaN,NaN,NaN
HRV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.9,6.5,6.1,4.3,4.9,5.0,5.0,4.7,NaN,NaN
HUN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.8,6.6,6.5,6.2,6.1,5.9,3.3,NaN,NaN,NaN
IRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.6,4.4,4.0,3.8,3.4,3.5,NaN,NaN,NaN,NaN
ISL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.6,3.6,3.5,3.3,2.9,2.8,2.7,2.3,2.3,2.2
ISR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.3,4.3,4.3,4.2,4.1,4.1,3.9,3.5,3.3,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,...,5.1,5.0,5.0,4.8,4.7,NaN,NaN,NaN,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.8,6.5,6.2,5.9,5.3,4.9,4.9,4.9,4.5,4.6
KAZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KGZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LTU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.7,6.3,5.9,5.1,4.2,3.8,3.5,3.9,4.0,NaN
LVA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.9,4.8,5.7,3.4,2.7,3.0,2.9,3.0,2.8,NaN
MDA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NLD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.1,5.3,5.1,4.6,4.5,1.5,1.5,NaN,NaN,NaN
NOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.2,3.4,4.0,3.9,3.5,3.2,NaN,NaN,NaN,NaN
NZL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.2,3.2,3.3,3.1,NaN,NaN,NaN,NaN,NaN,NaN
OWID_CZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OWID_YGS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
POL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.8,5.7,5.2,5.4,5.0,4.8,4.3,NaN,NaN,NaN
PRT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.5,4.4,4.0,4.0,3.9,3.9,3.1,NaN,NaN,NaN
ROU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.6,4.7,4.9,4.9,4.1,4.2,4.1,4.0,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SVK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.3,4.6,5.0,4.6,4.4,4.3,4.2,3.9,3.9,NaN
SVN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.8,6.6,7.4,6.6,6.2,5.7,5.8,4.8,4.6,NaN
SWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,0.1,0.1,0.1,0.1,0.2,...,4.5,4.2,4.0,3.7,3.6,3.5,3.5,3.3,3.2,NaN

## Death Rates Smoking Age

In [46]:
#SEAdeath_rates_smoking_age = death_rates_smoking_age[death_rates_smoking_age["Code"].isin(SEA_Countries_Code)]

In [47]:
death_rates_smoking_age = death_rates_smoking_age[["Code","Year","All_ages"]]

In [48]:
death_rates_smoking_age = death_rates_smoking_age.pivot_table("All_ages",["Code"],"Year")

In [49]:
death_rates_smoking_age["avg"]  = death_rates_smoking_age.mean(axis=1)

In [50]:
death_rates_smoking_age.columns = ["deathRate_"+str(x) for x in death_rates_smoking_age.columns]

In [51]:
death_rates_smoking_age

,deathRate_1990,deathRate_1991,deathRate_1992,deathRate_1993,deathRate_1994,deathRate_1995,deathRate_1996,deathRate_1997,deathRate_1998,deathRate_1999,...,deathRate_2009,deathRate_2010,deathRate_2011,deathRate_2012,deathRate_2013,deathRate_2014,deathRate_2015,deathRate_2016,deathRate_2017,deathRate_avg
Code,,,,,,,,,,,,,,,,,,,,,
AFG,63.895905,61.846347,53.436511,47.044347,45.799808,44.109036,42.616425,41.579362,40.860275,41.321832,...,31.247881,30.217384,29.381074,28.781991,28.220176,27.932338,28.022238,28.089774,28.127580,38.164768
AGO,55.336126,54.801691,54.408293,54.548736,54.350016,53.309461,51.136809,49.881300,51.131919,49.606460,...,37.483408,36.474249,35.738155,35.259244,34.368768,32.861465,32.254396,31.642266,31.241130,43.738552
ALB,74.382434,77.920510,76.411919,74.282222,71.288005,73.440844,78.489728,82.127025,79.656276,81.806467,...,111.709564,115.427724,120.979960,125.819761,131.187072,138.039816,142.594122,146.334116,150.430709,102.009951
AND,93.263925,90.882328,92.000151,92.692981,95.420198,97.005635,96.703684,96.117648,96.124110,96.674642,...,96.511500,97.479604,94.942909,94.117218,95.583268,96.203202,96.668713,98.398278,99.682713,95.704627
ARE,14.665647,15.020761,15.390174,15.793874,16.180918,16.545835,16.628807,16.636072,16.878859,17.186851,...,11.091580,12.190815,13.568159,15.153034,16.899626,18.850733,20.952964,23.309480,25.815678,16.368323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WSM,75.035643,75.388561,76.085998,76.470094,77.398664,78.205475,79.713423,79.546347,79.401109,79.533028,...,83.451667,83.799083,84.419556,85.233666,85.914899,86.721893,87.662583,88.713239,89.826213,81.374341
YEM,51.297551,50.484856,49.962191,49.534796,49.099109,48.579422,48.038072,47.483146,46.797839,46.129998,...,40.246683,39.816276,39.717770,39.648357,39.615008,39.668574,40.098227,40.632389,41.227174,44.052553
ZAF,76.176405,76.320858,77.521622,76.440371,79.258249,80.497273,88.541623,97.014771,99.182676,99.033443,...,79.872171,74.751062,69.731238,65.676539,62.209338,59.963270,58.783959,57.704270,54.446049,81.575526
ZMB,37.879420,39.128417,40.367554,41.620449,42.820869,43.914936,44.364940,44.249203,43.954032,43.088584,...,30.400465,29.980878,29.252326,28.394816,27.578072,26.831008,26.164978,25.600125,25.071954,35.539675
ZWE,44.532540,42.902861,43.497620,44.710857,46.819315,50.123618,51.597670,55.345337,60.900556,66.058458,...,79.614091,77.066961,73.360413,69.750158,66.609741,63.983527,62.211166,60.644339,59.228353,65.410028

## Combine the dataframes

In [52]:
cbd = pd.DataFrame().join([sales_per_day,stop_smoking,tobacco_useP, MilUsd, metricTons,death_rates_smoking_age], how="outer")

In [59]:
cbd

,sales_per_day_1875,sales_per_day_1880,sales_per_day_1885,sales_per_day_1890,sales_per_day_1895,sales_per_day_1900,sales_per_day_1901,sales_per_day_1902,sales_per_day_1903,sales_per_day_1904,...,deathRate_2009,deathRate_2010,deathRate_2011,deathRate_2012,deathRate_2013,deathRate_2014,deathRate_2015,deathRate_2016,deathRate_2017,deathRate_avg
Code,,,,,,,,,,,,,,,,,,,,,
ARM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,157.604674,158.193740,157.347861,154.793002,151.965976,152.945949,155.521200,157.698508,160.937278,146.401481
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.937099,90.311414,89.008526,86.244432,85.153877,86.258485,86.949177,87.432138,90.044181,112.444347
AUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,133.635017,133.228540,132.642904,132.660391,132.734686,132.167783,132.558398,130.503704,130.810203,149.268659
AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,104.117496,105.727189,107.543445,108.698056,110.439626,111.145857,112.375811,115.433004,119.478056,105.697292
BEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,210.104951,205.116231,202.717193,201.716429,196.704442,187.920342,186.732065,180.402488,177.372323,223.091072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
OWID_WRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.514093,93.410851,92.921823,92.438707,91.444032,91.596550,92.865602,93.278283,92.914638,99.092821
PRI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.800901,50.108974,51.618709,49.528151,49.445728,48.576678,47.753056,49.456884,50.895463,51.929262
PSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.865474,23.943285,23.277929,22.956603,22.702146,22.725609,22.819894,23.017349,23.464853,29.086355
TWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,102.605123,104.253583,110.350609,109.865905,109.689112,113.330414,113.010432,116.461172,117.723921,94.625588
VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.650010,67.006587,68.107920,70.597984,72.936038,75.415334,78.519228,79.070609,81.079558,56.560581

In [54]:
cbd.isnull().sum()

sales_per_day_1875    206
sales_per_day_1880    206
sales_per_day_1885    206
sales_per_day_1890    206
sales_per_day_1895    206
                     ...
deathRate_2014         11
deathRate_2015         11
deathRate_2016         11
deathRate_2017         11
deathRate_avg          11
Length: 233, dtype: int64

In [55]:
cbd.isnull().sum(axis=1)

Code
ARM         154
AUS          73
AUT          81
AZE         115
BEL          69
           ...
OWID_WRL    204
PRI         204
PSE         204
TWN         204
VIR         204
Length: 207, dtype: int64

In [58]:
pd.to_pickle(drsmaDict,"Data/countryToCode.pkl")

In [293]:
pd.to_pickle(cbd,"Data/combined_ww.pkl")

In [1]:
1

1

In [61]:
list(cbd.columns)

['sales_per_day_1875',
 'sales_per_day_1880',
 'sales_per_day_1885',
 'sales_per_day_1890',
 'sales_per_day_1895',
 'sales_per_day_1900',
 'sales_per_day_1901',
 'sales_per_day_1902',
 'sales_per_day_1903',
 'sales_per_day_1904',
 'sales_per_day_1905',
 'sales_per_day_1906',
 'sales_per_day_1907',
 'sales_per_day_1908',
 'sales_per_day_1909',
 'sales_per_day_1910',
 'sales_per_day_1911',
 'sales_per_day_1912',
 'sales_per_day_1913',
 'sales_per_day_1914',
 'sales_per_day_1915',
 'sales_per_day_1916',
 'sales_per_day_1917',
 'sales_per_day_1918',
 'sales_per_day_1919',
 'sales_per_day_1920',
 'sales_per_day_1921',
 'sales_per_day_1922',
 'sales_per_day_1923',
 'sales_per_day_1924',
 'sales_per_day_1925',
 'sales_per_day_1926',
 'sales_per_day_1927',
 'sales_per_day_1928',
 'sales_per_day_1929',
 'sales_per_day_1930',
 'sales_per_day_1931',
 'sales_per_day_1932',
 'sales_per_day_1933',
 'sales_per_day_1934',
 'sales_per_day_1935',
 'sales_per_day_1936',
 'sales_per_day_1937',
 'sales_per_day_1938',
 'sales_per_day_1939',
 'sales_per_day_1940',
 'sales_per_day_1941',
 'sales_per_day_1942',
 'sales_per_day_1943',
 'sales_per_day_1944',
 'sales_per_day_1945',
 'sales_per_day_1946',
 'sales_per_day_1947',
 'sales_per_day_1948',
 'sales_per_day_1949',
 'sales_per_day_1950',
 'sales_per_day_1951',
 'sales_per_day_1952',
 'sales_per_day_1953',
 'sales_per_day_1954',
 'sales_per_day_1955',
 'sales_per_day_1956',
 'sales_per_day_1957',
 'sales_per_day_1958',
 'sales_per_day_1959',
 'sales_per_day_1960',
 'sales_per_day_1961',
 'sales_per_day_1962',
 'sales_per_day_1963',
 'sales_per_day_1964',
 'sales_per_day_1965',
 'sales_per_day_1966',
 'sales_per_day_1967',
 'sales_per_day_1968',
 'sales_per_day_1969',
 'sales_per_day_1970',
 'sales_per_day_1971',
 'sales_per_day_1972',
 'sales_per_day_1973',
 'sales_per_day_1974',
 'sales_per_day_1975',
 'sales_per_day_1976',
 'sales_per_day_1977',
 'sales_per_day_1978',
 'sales_per_day_1979',
 'sales_per_day_1980',
 'sales_per_day_1981',
 'sales_per_day_1982',
 'sales_per_day_1983',
 'sales_per_day_1984',
 'sales_per_day_1985',
 'sales_per_day_1986',
 'sales_per_day_1987',
 'sales_per_day_1988',
 'sales_per_day_1989',
 'sales_per_day_1990',
 'sales_per_day_1991',
 'sales_per_day_1992',
 'sales_per_day_1993',
 'sales_per_day_1994',
 'sales_per_day_1995',
 'sales_per_day_1996',
 'sales_per_day_1997',
 'sales_per_day_1998',
 'sales_per_day_1999',
 'sales_per_day_2000',
 'sales_per_day_2001',
 'sales_per_day_2002',
 'sales_per_day_2003',
 'sales_per_day_2004',
 'sales_per_day_2005',
 'sales_per_day_2006',
 'sales_per_day_2007',
 'sales_per_day_2008',
 'sales_per_day_2009',
 'sales_per_day_2010',
 'sales_per_day_2011',
 'sales_per_day_2012',
 'sales_per_day_2013',
 'sales_per_day_2014',
 'sales_per_day_2015',
 'AvgCigarettePriceDollars_2012',
 'AvgCigarettePriceDollars_2014',
 'AvgTaxesAsPctCigarettePrice_2012',
 'AvgTaxesAsPctCigarettePrice_2014',
 'EnforceBansTobaccoAd_2007',
 'EnforceBansTobaccoAd_2010',
 'EnforceBansTobaccoAd_2012',
 'EnforceBansTobaccoAd_2014',
 'HelpToQuit_2007',
 'HelpToQuit_2010',
 'HelpToQuit_2012',
 'HelpToQuit_2014',
 'Both sexes_2000',
 'Female_2000',
 'Male_2000',
 'Both sexes_2005',
 'Female_2005',
 'Male_2005',
 'Both sexes_2010',
 'Female_2010',
 'Male_2010',
 'Both sexes_2013',
 'Female_2013',
 'Male_2013',
 'Both sexes_2014',
 'Female_2014',
 'Male_2014',
 'Both sexes_2015',
 'Female_2015',
 'Male_2015',
 'Both sexes_2016',
 'Female_2016',
 'Male_2016',
 'Both sexes_2017',
 'Female_2017',
 'Male_2017',
 'Both sexes_2018',
 'Female_2018',
 'Male_2018',
 'MilUsd_1995',
 'MilUsd_1996',
 'MilUsd_1997',
 'MilUsd_1998',
 'MilUsd_1999',
 'MilUsd_2000',
 'MilUsd_2001',
 'MilUsd_2002',
 'MilUsd_2003',
 'MilUsd_2004',
 'MilUsd_2005',
 'MilUsd_2006',
 'MilUsd_2007',
 'MilUsd_2008',
 'MilUsd_2009',
 'MilUsd_2010',
 'MilUsd_2011',
 'MilUsd_2012',
 'MilUsd_2013',
 'MilUsd_2014',
 'MilUsd_2015',
 'MilUsd_2016',
 'metricTons_1995',
 'metricTons_1996',
 'metricTons_1997',
 'metricTons_1998',
 'metricTons_1999',
 'metricTons_2000',
 'metricTons_2001',
 'metricTons_2002',
 'metricTons_2003',
 'metricTons_2004',
 'metricTons_2005',
 'metricTons_2006',
 'metricTons_2007',
 'metricTons_2008',
 'metricTons_2009',
 'metricTons_2010',
 'metricTons_2011',
 'metricTons_2012',
 'metricTons_2013',
 'metricTons_2014',
 'metricTons_2015',
 'metricTons_2016',
 'deathRate_1990',
 'deathRate_1991',
 'deathRate_1992',
 'deathRate_1993',
 'deathRate_1994',
 'deathRate_1995',
 'deathRate_1996',
 'deathRate_1997',
 'deathRate_1998',
 'deathRate_1999',
 'deathRate_2000',
 'deathRate_2001',
 'deathRate_2002',
 'deathRate_2003',
 'deathRate_2004',
 'deathRate_2005',
 'deathRate_2006',
 'deathRate_2007',
 'deathRate_2008',
 'deathRate_2009',
 'deathRate_2010',
 'deathRate_2011',
 'deathRate_2012',
 'deathRate_2013',
 'deathRate_2014',
 'deathRate_2015',
 'deathRate_2016',
 'deathRate_2017',
 'deathRate_avg']