In [2]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA, FactorAnalysis

In [4]:
allCbd = pd.read_pickle("Data/allCombined.pkl")

In [66]:
allCbd[[ 'sales_per_day_1875',
 'sales_per_day_1880',
 'sales_per_day_1885',
 'sales_per_day_1890',
 'sales_per_day_1895',
 'sales_per_day_1900',
 'sales_per_day_1901',
 'sales_per_day_1902',
 'sales_per_day_1903',
 'sales_per_day_1904',
 'sales_per_day_1905',
 'sales_per_day_1906',
 'sales_per_day_1907',
 'sales_per_day_1908',
 'sales_per_day_1909',
 'sales_per_day_1910',
 'sales_per_day_1911',
 'sales_per_day_1912',
 'sales_per_day_1913',
 'sales_per_day_1914',
 'sales_per_day_1915',
 'sales_per_day_1916',
 'sales_per_day_1917',
 'sales_per_day_1918',
 'sales_per_day_1919',
 'sales_per_day_1920',
 'sales_per_day_1921',
 'sales_per_day_1922',
 'sales_per_day_1923',
 'sales_per_day_1924',
 'sales_per_day_1925',
 'sales_per_day_1926',
 'sales_per_day_1927',
 'sales_per_day_1928',
 'sales_per_day_1929',
 'sales_per_day_1930',
 'sales_per_day_1931',
 'sales_per_day_1932',
 'sales_per_day_1933',
 'sales_per_day_1934',
 'sales_per_day_1935',
 'sales_per_day_1936',
 'sales_per_day_1937',
 'sales_per_day_1938',
 'sales_per_day_1939',
 'sales_per_day_1940',
 'sales_per_day_1941',
 'sales_per_day_1942',
 'sales_per_day_1943',
 'sales_per_day_1944',
 'sales_per_day_1945',
 'sales_per_day_1946',
 'sales_per_day_1947',
 'sales_per_day_1948',
 'sales_per_day_1949',
 'sales_per_day_1950',
 'sales_per_day_1951',
 'sales_per_day_1952',
 'sales_per_day_1953',
 'sales_per_day_1954',
 'sales_per_day_1955',
 'sales_per_day_1956',
 'sales_per_day_1957',
 'sales_per_day_1958',
 'sales_per_day_1959',
 'sales_per_day_1960',
 'sales_per_day_1961',
 'sales_per_day_1962',
 'sales_per_day_1963',
 'sales_per_day_1964',
 'sales_per_day_1965',
 'sales_per_day_1966',
 'sales_per_day_1967',
 'sales_per_day_1968',
 'sales_per_day_1969',
 'sales_per_day_1970',
 'sales_per_day_1971',
 'sales_per_day_1972',
 'sales_per_day_1973',
 'sales_per_day_1974',
 'sales_per_day_1975',
 'sales_per_day_1976',
 'sales_per_day_1977',
 'sales_per_day_1978',
 'sales_per_day_1979',
 'sales_per_day_1980',
 'sales_per_day_1981',
 'sales_per_day_1982',
 'sales_per_day_1983',
 'sales_per_day_1984',
 'sales_per_day_1985',
 'sales_per_day_1986',
 'sales_per_day_1987',
 'sales_per_day_1988',
 'sales_per_day_1989',
 'sales_per_day_1990',
 'sales_per_day_1991',
 'sales_per_day_1992',
 'sales_per_day_1993',
 'sales_per_day_1994',
 'sales_per_day_1995',
 'sales_per_day_1996',
 'sales_per_day_1997',
 'sales_per_day_1998',
 'sales_per_day_1999',
 'sales_per_day_2000',
 'sales_per_day_2001',
 'sales_per_day_2002',
 'sales_per_day_2003',
 'sales_per_day_2004',
 'sales_per_day_2005',
 'sales_per_day_2006',
 'sales_per_day_2007',
 'sales_per_day_2008',
 'sales_per_day_2009',
 'sales_per_day_2010',
 'sales_per_day_2011',
 'sales_per_day_2012',
 'sales_per_day_2013',
 'sales_per_day_2014',
 'sales_per_day_2015',
]].mean(axis=1,skipna=True).isnull().sum()

138

In [86]:
allCbd.drop([ 'sales_per_day_1875',
 'sales_per_day_1880',
 'sales_per_day_1885',
 'sales_per_day_1890',
 'sales_per_day_1895',
 'sales_per_day_1900',
 'sales_per_day_1901',
 'sales_per_day_1902',
 'sales_per_day_1903',
 'sales_per_day_1904',
 'sales_per_day_1905',
 'sales_per_day_1906',
 'sales_per_day_1907',
 'sales_per_day_1908',
 'sales_per_day_1909',
 'sales_per_day_1910',
 'sales_per_day_1911',
 'sales_per_day_1912',
 'sales_per_day_1913',
 'sales_per_day_1914',
 'sales_per_day_1915',
 'sales_per_day_1916',
 'sales_per_day_1917',
 'sales_per_day_1918',
 'sales_per_day_1919',
 'sales_per_day_1920',
 'sales_per_day_1921',
 'sales_per_day_1922',
 'sales_per_day_1923',
 'sales_per_day_1924',
 'sales_per_day_1925',
 'sales_per_day_1926',
 'sales_per_day_1927',
 'sales_per_day_1928',
 'sales_per_day_1929',
 'sales_per_day_1930',
 'sales_per_day_1931',
 'sales_per_day_1932',
 'sales_per_day_1933',
 'sales_per_day_1934',
 'sales_per_day_1935',
 'sales_per_day_1936',
 'sales_per_day_1937',
 'sales_per_day_1938',
 'sales_per_day_1939',
 'sales_per_day_1940',
 'sales_per_day_1941',
 'sales_per_day_1942',
 'sales_per_day_1943',
 'sales_per_day_1944',
 'sales_per_day_1945',
 'sales_per_day_1946',
 'sales_per_day_1947',
 'sales_per_day_1948',
 'sales_per_day_1949',
 'sales_per_day_1950',
 'sales_per_day_1951',
 'sales_per_day_1952',
 'sales_per_day_1953',
 'sales_per_day_1954',
 'sales_per_day_1955',
 'sales_per_day_1956',
 'sales_per_day_1957',
 'sales_per_day_1958',
 'sales_per_day_1959',
 'sales_per_day_1960',
 'sales_per_day_1961',
 'sales_per_day_1962',
 'sales_per_day_1963',
 'sales_per_day_1964',
 'sales_per_day_1965',
 'sales_per_day_1966',
 'sales_per_day_1967',
 'sales_per_day_1968',
 'sales_per_day_1969',
 'sales_per_day_1970',
 'sales_per_day_1971',
 'sales_per_day_1972',
 'sales_per_day_1973',
 'sales_per_day_1974',
 'sales_per_day_1975',
 'sales_per_day_1976',
 'sales_per_day_1977',
 'sales_per_day_1978',
 'sales_per_day_1979',
 'sales_per_day_1980',
 'sales_per_day_1981',
 'sales_per_day_1982',
 'sales_per_day_1983',
 'sales_per_day_1984',
 'sales_per_day_1985',
 'sales_per_day_1986',
 'sales_per_day_1987',
 'sales_per_day_1988',
 'sales_per_day_1989',
 'sales_per_day_1990',
 'sales_per_day_1991',
 'sales_per_day_1992',
 'sales_per_day_1993',
 'sales_per_day_1994',
 'sales_per_day_1995',
 'sales_per_day_1996',
 'sales_per_day_1997',
 'sales_per_day_1998',
 'sales_per_day_1999',
 'sales_per_day_2000',
 'sales_per_day_2001',
 'sales_per_day_2002',
 'sales_per_day_2003',
 'sales_per_day_2004',
 'sales_per_day_2005',
 'sales_per_day_2006',
 'sales_per_day_2007',
 'sales_per_day_2008',
 'sales_per_day_2009',
 'sales_per_day_2010',
 'sales_per_day_2011',
 'sales_per_day_2012',
 'sales_per_day_2013',
 'sales_per_day_2014',
 'sales_per_day_2015',
],axis=1,inplace=True)

In [91]:
list(allCbd.columns)

['Code',
 'AvgTaxesAsPctCigarettePrice_2012',
 'AvgTaxesAsPctCigarettePrice_2014',
 'EnforceBansTobaccoAd_2007',
 'EnforceBansTobaccoAd_2010',
 'EnforceBansTobaccoAd_2012',
 'EnforceBansTobaccoAd_2014',
 'HelpToQuit_2007',
 'HelpToQuit_2010',
 'HelpToQuit_2012',
 'HelpToQuit_2014',
 'Both sexes_2000',
 'Female_2000',
 'Male_2000',
 'Both sexes_2005',
 'Female_2005',
 'Male_2005',
 'Both sexes_2010',
 'Female_2010',
 'Male_2010',
 'Both sexes_2013',
 'Female_2013',
 'Male_2013',
 'Both sexes_2014',
 'Female_2014',
 'Male_2014',
 'Both sexes_2015',
 'Female_2015',
 'Male_2015',
 'Both sexes_2016',
 'Female_2016',
 'Male_2016',
 'Both sexes_2017',
 'Female_2017',
 'Male_2017',
 'Both sexes_2018',
 'Female_2018',
 'Male_2018',
 'MilUsd_1995',
 'MilUsd_1996',
 'MilUsd_1997',
 'MilUsd_1998',
 'MilUsd_1999',
 'MilUsd_2000',
 'MilUsd_2001',
 'MilUsd_2002',
 'MilUsd_2003',
 'MilUsd_2004',
 'MilUsd_2005',
 'MilUsd_2006',
 'MilUsd_2007',
 'MilUsd_2008',
 'MilUsd_2009',
 'MilUsd_2010',
 'MilUsd_2011',
 'MilUsd_2012',
 'MilUsd_2013',
 'MilUsd_2014',
 'MilUsd_2015',
 'MilUsd_2016',
 'metricTons_metricTons_1995',
 'metricTons_metricTons_1996',
 'metricTons_metricTons_1997',
 'metricTons_metricTons_1998',
 'metricTons_metricTons_1999',
 'metricTons_metricTons_2000',
 'metricTons_metricTons_2001',
 'metricTons_metricTons_2002',
 'metricTons_metricTons_2003',
 'metricTons_metricTons_2004',
 'metricTons_metricTons_2005',
 'metricTons_metricTons_2006',
 'metricTons_metricTons_2007',
 'metricTons_metricTons_2008',
 'metricTons_metricTons_2009',
 'metricTons_metricTons_2010',
 'metricTons_metricTons_2011',
 'metricTons_metricTons_2012',
 'metricTons_metricTons_2013',
 'metricTons_metricTons_2014',
 'metricTons_metricTons_2015',
 'metricTons_metricTons_2016',
 'deathRate_1990',
 'deathRate_1991',
 'deathRate_1992',
 'deathRate_1993',
 'deathRate_1994',
 'deathRate_1995',
 'deathRate_1996',
 'deathRate_1997',
 'deathRate_1998',
 'deathRate_1999',
 'deathRate_2000',
 'deathRate_2001',
 'deathRate_2002',
 'deathRate_2003',
 'deathRate_2004',
 'deathRate_2005',
 'deathRate_2006',
 'deathRate_2007',
 'deathRate_2008',
 'deathRate_2009',
 'deathRate_2010',
 'deathRate_2011',
 'deathRate_2012',
 'deathRate_2013',
 'deathRate_2014',
 'deathRate_2015',
 'deathRate_2016',
 'deathRate_2017',
 'deathRate_avg',
 'EnforceBansTobaccoAd_2016',
 'NATL_Country',
 'NATL_Region',
 'NATL_Population',
 'NATL_Area (sq. mi.)',
 'NATL_Pop. Density (per sq. mi.)',
 'NATL_Coastline (coast/area ratio)',
 'NATL_Net migration',
 'NATL_Infant mortality (per 1000 births)',
 'NATL_GDP ($ per capita)',
 'NATL_Literacy (%)',
 'NATL_Phones (per 1000)',
 'NATL_Arable (%)',
 'NATL_Crops (%)',
 'NATL_Other (%)',
 'NATL_Climate',
 'NATL_Birthrate',
 'NATL_Deathrate',
 'NATL_Agriculture',
 'NATL_Industry',
 'NATL_Service',
 'AvgCigarettePriceDollars_Avg']

In [88]:
allCbd.loc[:,allCbd.isnull().sum()<80].isnull().sum().unique()

array([ 0, 78,  6, 41,  1, 18,  2,  7, 73], dtype=int64)

In [89]:
allCbd["AvgCigarettePriceDollars_Avg"] = allCbd[['AvgCigarettePriceDollars_2012',
 'AvgCigarettePriceDollars_2014']].mean(axis=1)

KeyError: "None of [Index(['AvgCigarettePriceDollars_2012', 'AvgCigarettePriceDollars_2014'], dtype='object')] are in the [columns]"

In [90]:
allCbd.drop(['AvgCigarettePriceDollars_2012',
 'AvgCigarettePriceDollars_2014'],axis=1,inplace=True)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (Temp/ipykernel_28400/4126721525.py, line 2)

In [94]:
allCbd["AvgTaxesAsPctCigarettePrice_Avg"] = allCbd[['AvgTaxesAsPctCigarettePrice_2012',
 'AvgTaxesAsPctCigarettePrice_2014']].mean(axis=1)

In [95]:
allCbd.drop(['AvgTaxesAsPctCigarettePrice_2012',
 'AvgTaxesAsPctCigarettePrice_2014'],axis=1,inplace=True)

In [120]:
list(allCbd.loc[:,allCbd.isnull().sum()>80].columns)

['MilUsd_1995',
 'MilUsd_1996',
 'MilUsd_1997',
 'MilUsd_1998',
 'MilUsd_1999',
 'MilUsd_2000',
 'MilUsd_2001',
 'MilUsd_2002',
 'MilUsd_2003',
 'MilUsd_2004',
 'MilUsd_2005',
 'MilUsd_2006',
 'MilUsd_2007',
 'MilUsd_2008',
 'MilUsd_2009',
 'MilUsd_2010',
 'MilUsd_2011',
 'MilUsd_2012',
 'MilUsd_2013',
 'MilUsd_2014',
 'MilUsd_2015',
 'MilUsd_2016',
 'metricTons_metricTons_1995',
 'metricTons_metricTons_1996',
 'metricTons_metricTons_1997',
 'metricTons_metricTons_1998',
 'metricTons_metricTons_1999',
 'metricTons_metricTons_2000',
 'metricTons_metricTons_2001',
 'metricTons_metricTons_2002',
 'metricTons_metricTons_2003',
 'metricTons_metricTons_2004',
 'metricTons_metricTons_2005',
 'metricTons_metricTons_2006',
 'metricTons_metricTons_2007',
 'metricTons_metricTons_2008',
 'metricTons_metricTons_2009',
 'metricTons_metricTons_2010',
 'metricTons_metricTons_2011',
 'metricTons_metricTons_2012',
 'metricTons_metricTons_2013',
 'metricTons_metricTons_2014',
 'metricTons_metricTons_2015',
 'metricTons_metricTons_2016']

In [111]:
allCbd[['MilUsd_1995',
 'MilUsd_1996',
 'MilUsd_1997',
 'MilUsd_1998',
 'MilUsd_1999',
 'MilUsd_2000',
 'MilUsd_2001',
 'MilUsd_2002',
 'MilUsd_2003',
 'MilUsd_2004',
 'MilUsd_2005',
 'MilUsd_2006',
 'MilUsd_2007',
 'MilUsd_2008',
 'MilUsd_2009',
 'MilUsd_2010',
 'MilUsd_2011',
 'MilUsd_2012',
 'MilUsd_2013',
 'MilUsd_2014',
 'MilUsd_2015',
 'MilUsd_2016']].mean(axis=1).isnull().sum()

132

In [104]:
allCbd[['metricTons_metricTons_1995',
 'metricTons_metricTons_1996',
 'metricTons_metricTons_1997',
 'metricTons_metricTons_1998',
 'metricTons_metricTons_1999',
 'metricTons_metricTons_2000',
 'metricTons_metricTons_2001',
 'metricTons_metricTons_2002',
 'metricTons_metricTons_2003',
 'metricTons_metricTons_2004',
 'metricTons_metricTons_2005',
 'metricTons_metricTons_2006',
 'metricTons_metricTons_2007',
 'metricTons_metricTons_2008',
 'metricTons_metricTons_2009',
 'metricTons_metricTons_2010',
 'metricTons_metricTons_2011',
 'metricTons_metricTons_2012',
 'metricTons_metricTons_2013',
 'metricTons_metricTons_2014',
 'metricTons_metricTons_2015',
 'metricTons_metricTons_2016']].mean(axis=1).notnull().sum()

73

In [118]:
allCbd[['metricTons_metricTons_1995',
 'metricTons_metricTons_1996',
 'metricTons_metricTons_1997',
 'metricTons_metricTons_1998',
 'metricTons_metricTons_1999',
 'metricTons_metricTons_2000',
 'metricTons_metricTons_2001',
 'metricTons_metricTons_2002',
 'metricTons_metricTons_2003',
 'metricTons_metricTons_2004',
 'metricTons_metricTons_2005',
 'metricTons_metricTons_2006',
 'metricTons_metricTons_2007',
 'metricTons_metricTons_2008',
 'metricTons_metricTons_2009',
 'metricTons_metricTons_2010',
 'metricTons_metricTons_2011',
 'metricTons_metricTons_2012',
 'metricTons_metricTons_2013',
 'metricTons_metricTons_2014',
 'metricTons_metricTons_2015',
 'metricTons_metricTons_2016']].mean(axis=1).isnull().sum()

106

In [119]:
allCbd[['metricTons_metricTons_1995',
 'metricTons_metricTons_1996',
 'metricTons_metricTons_1997',
 'metricTons_metricTons_1998',
 'metricTons_metricTons_1999',
 'metricTons_metricTons_2000',
 'metricTons_metricTons_2001',
 'metricTons_metricTons_2002',
 'metricTons_metricTons_2003',
 'metricTons_metricTons_2004',
 'metricTons_metricTons_2005',
 'metricTons_metricTons_2006',
 'metricTons_metricTons_2007',
 'metricTons_metricTons_2008',
 'metricTons_metricTons_2009',
 'metricTons_metricTons_2010',
 'metricTons_metricTons_2011',
 'metricTons_metricTons_2012',
 'metricTons_metricTons_2013',
 'metricTons_metricTons_2014',
 'metricTons_metricTons_2015',
 'metricTons_metricTons_2016']].notnull().sum()

metricTons_metricTons_1995    39
metricTons_metricTons_1996    37
metricTons_metricTons_1997    40
metricTons_metricTons_1998    41
metricTons_metricTons_1999    41
metricTons_metricTons_2000    42
metricTons_metricTons_2001    40
metricTons_metricTons_2002    41
metricTons_metricTons_2003    43
metricTons_metricTons_2004    45
metricTons_metricTons_2005    42
metricTons_metricTons_2006    39
metricTons_metricTons_2007    35
metricTons_metricTons_2008    30
metricTons_metricTons_2009    29
metricTons_metricTons_2010    24
metricTons_metricTons_2011    24
metricTons_metricTons_2012    24
metricTons_metricTons_2013    27
metricTons_metricTons_2014    28
metricTons_metricTons_2015    27
metricTons_metricTons_2016    32
dtype: int64

In [124]:
fun = allCbd.loc[:,allCbd.isnull().sum()<80]

In [126]:
fun.columns

Index(['Code', 'EnforceBansTobaccoAd_2007', 'EnforceBansTobaccoAd_2010',
       'EnforceBansTobaccoAd_2012', 'EnforceBansTobaccoAd_2014',
       'HelpToQuit_2007', 'HelpToQuit_2010', 'HelpToQuit_2012',
       'HelpToQuit_2014', 'Both sexes_2000', 'Female_2000', 'Male_2000',
       'Both sexes_2005', 'Female_2005', 'Male_2005', 'Both sexes_2010',
       'Female_2010', 'Male_2010', 'Both sexes_2013', 'Female_2013',
       'Male_2013', 'Both sexes_2014', 'Female_2014', 'Male_2014',
       'Both sexes_2015', 'Female_2015', 'Male_2015', 'Both sexes_2016',
       'Female_2016', 'Male_2016', 'Both sexes_2017', 'Female_2017',
       'Male_2017', 'Both sexes_2018', 'Female_2018', 'Male_2018',
       'deathRate_1990', 'deathRate_1991', 'deathRate_1992', 'deathRate_1993',
       'deathRate_1994', 'deathRate_1995', 'deathRate_1996', 'deathRate_1997',
       'deathRate_1998', 'deathRate_1999', 'deathRate_2000', 'deathRate_2001',
       'deathRate_2002', 'deathRate_2003', 'deathRate_2004', 'deathRate_2005',
       'deathRate_2006', 'deathRate_2007', 'deathRate_2008', 'deathRate_2009',
       'deathRate_2010', 'deathRate_2011', 'deathRate_2012', 'deathRate_2013',
       'deathRate_2014', 'deathRate_2015', 'deathRate_2016', 'deathRate_2017',
       'deathRate_avg', 'EnforceBansTobaccoAd_2016', 'NATL_Country',
       'NATL_Region', 'NATL_Population', 'NATL_Area (sq. mi.)',
       'NATL_Pop. Density (per sq. mi.)', 'NATL_Coastline (coast/area ratio)',
       'NATL_Net migration', 'NATL_Infant mortality (per 1000 births)',
       'NATL_GDP ($ per capita)', 'NATL_Literacy (%)',
       'NATL_Phones (per 1000)', 'NATL_Arable (%)', 'NATL_Crops (%)',
       'NATL_Other (%)', 'NATL_Climate', 'NATL_Birthrate', 'NATL_Deathrate',
       'NATL_Agriculture', 'NATL_Industry', 'NATL_Service',
       'AvgCigarettePriceDollars_Avg', 'AvgTaxesAsPctCigarettePrice_Avg'],
      dtype='object')

In [128]:
fun = fun.drop(['deathRate_1990', 'deathRate_1991', 'deathRate_1992', 'deathRate_1993',
       'deathRate_1994', 'deathRate_1995', 'deathRate_1996', 'deathRate_1997',
       'deathRate_1998', 'deathRate_1999', 'deathRate_2000', 'deathRate_2001',
       'deathRate_2002', 'deathRate_2003', 'deathRate_2004', 'deathRate_2005',
       'deathRate_2006', 'deathRate_2007', 'deathRate_2008', 'deathRate_2009',
       'deathRate_2010', 'deathRate_2011', 'deathRate_2012', 'deathRate_2013',
       'deathRate_2014', 'deathRate_2015', 'deathRate_2016', 'deathRate_2017'],axis=1)

In [134]:
funDR = fun.drop(['Both sexes_2000', 'Female_2000', 'Male_2000',
       'Both sexes_2005', 'Female_2005', 'Male_2005', 'Both sexes_2010',
       'Female_2010', 'Male_2010', 'Both sexes_2013', 'Female_2013',
       'Male_2013', 'Both sexes_2014', 'Female_2014', 'Male_2014',
       'Both sexes_2015', 'Female_2015', 'Male_2015', 'Both sexes_2016',
       'Female_2016', 'Male_2016', 'Both sexes_2017', 'Female_2017',
       'Male_2017', 'Both sexes_2018', 'Female_2018', 'Male_2018'],axis=1)

0      29.244444
1      19.577778
2      34.755556
3      22.144444
4      26.555556
         ...
174          NaN
175          NaN
176          NaN
177          NaN
178          NaN
Length: 179, dtype: float64

In [140]:
funBS = fun.copy()
funBS["Both sexes"] = fun[['Both sexes_2000',
'Both sexes_2005',
'Both sexes_2010',
'Both sexes_2013',
'Both sexes_2014',
'Both sexes_2015',
'Both sexes_2016',
'Both sexes_2017',
'Both sexes_2018']].mean(axis=1)
funBS.drop(['Both sexes_2000', 'Female_2000', 'Male_2000',
       'Both sexes_2005', 'Female_2005', 'Male_2005', 'Both sexes_2010',
       'Female_2010', 'Male_2010', 'Both sexes_2013', 'Female_2013',
       'Male_2013', 'Both sexes_2014', 'Female_2014', 'Male_2014',
       'Both sexes_2015', 'Female_2015', 'Male_2015', 'Both sexes_2016',
       'Female_2016', 'Male_2016', 'Both sexes_2017', 'Female_2017',
       'Male_2017', 'Both sexes_2018', 'Female_2018', 'Male_2018'],axis=1,inplace=True)

In [142]:
funM = fun.copy()
funM["Male"] = fun[['Male_2000',
'Male_2005',
'Male_2010',
'Male_2013',
'Male_2014',
'Male_2015',
'Male_2016',
'Male_2017',
'Male_2018']].mean(axis=1)
funM.drop(['Both sexes_2000', 'Female_2000', 'Male_2000',
       'Both sexes_2005', 'Female_2005', 'Male_2005', 'Both sexes_2010',
       'Female_2010', 'Male_2010', 'Both sexes_2013', 'Female_2013',
       'Male_2013', 'Both sexes_2014', 'Female_2014', 'Male_2014',
       'Both sexes_2015', 'Female_2015', 'Male_2015', 'Both sexes_2016',
       'Female_2016', 'Male_2016', 'Both sexes_2017', 'Female_2017',
       'Male_2017', 'Both sexes_2018', 'Female_2018', 'Male_2018'],axis=1,inplace=True)

In [143]:
funF = fun.copy()
funF["Male"] = fun[['Female_2000',
'Female_2005',
'Female_2010',
'Female_2013',
'Female_2014',
'Female_2015',
'Female_2016',
'Female_2017',
'Female_2018']].mean(axis=1)
funF.drop(['Both sexes_2000', 'Female_2000', 'Male_2000',
       'Both sexes_2005', 'Female_2005', 'Male_2005', 'Both sexes_2010',
       'Female_2010', 'Male_2010', 'Both sexes_2013', 'Female_2013',
       'Male_2013', 'Both sexes_2014', 'Female_2014', 'Male_2014',
       'Both sexes_2015', 'Female_2015', 'Male_2015', 'Both sexes_2016',
       'Female_2016', 'Male_2016', 'Both sexes_2017', 'Female_2017',
       'Male_2017', 'Both sexes_2018', 'Female_2018', 'Male_2018'],axis=1,inplace=True)

In [144]:
funF

,Code,EnforceBansTobaccoAd_2007,EnforceBansTobaccoAd_2010,EnforceBansTobaccoAd_2012,EnforceBansTobaccoAd_2014,HelpToQuit_2007,HelpToQuit_2010,HelpToQuit_2012,HelpToQuit_2014,deathRate_avg,...,NATL_Other (%),NATL_Climate,NATL_Birthrate,NATL_Deathrate,NATL_Agriculture,NATL_Industry,NATL_Service,AvgCigarettePriceDollars_Avg,AvgTaxesAsPctCigarettePrice_Avg,Male
0,ARM,2.0,2.0,2.0,2.0,3.0,3.0,4.0,4.0,146.401481,...,80.15,4.0,12.07,8.23,0.239,0.343,0.418,1.715,41.25,1.855556
1,AUS,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,112.444347,...,93.41,1.0,12.14,7.51,0.038,0.262,0.700,9.440,60.75,17.033333
2,AUT,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,149.268659,...,82.23,3.0,8.74,9.76,0.018,0.304,0.678,5.155,74.95,32.355556
3,AZE,4.0,4.0,4.0,4.0,2.0,3.0,3.0,3.0,105.697292,...,77.66,1.0,20.74,9.75,0.141,0.457,0.402,2.225,18.70,0.233333
4,BEL,4.0,4.0,4.0,4.0,5.0,4.0,4.0,5.0,223.091072,...,76.32,3.0,10.38,10.27,0.010,0.240,0.749,5.685,76.40,23.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,BMU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.296021,...,80.00,2.0,11.40,7.74,0.010,0.100,0.890,NaN,NaN,NaN
175,GRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.938202,...,100.00,1.0,15.93,7.84,NaN,NaN,NaN,NaN,NaN,NaN
176,GUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.908373,...,74.55,2.0,18.79,4.48,NaN,NaN,NaN,NaN,NaN,NaN
177,PRI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.929262,...,90.53,2.0,12.77,7.65,0.010,0.450,0.540,NaN,NaN,NaN
178,TWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.625588,...,75.00,2.0,12.56,6.48,0.018,0.259,0.723,NaN,NaN,NaN

In [148]:
funDR.isnull().sum()

Code                                        0
EnforceBansTobaccoAd_2007                   6
EnforceBansTobaccoAd_2010                   6
EnforceBansTobaccoAd_2012                   6
EnforceBansTobaccoAd_2014                   6
HelpToQuit_2007                             6
HelpToQuit_2010                             6
HelpToQuit_2012                             6
HelpToQuit_2014                             6
deathRate_avg                               6
EnforceBansTobaccoAd_2016                   6
NATL_Country                                0
NATL_Region                                 0
NATL_Population                             0
NATL_Area (sq. mi.)                         0
NATL_Pop. Density (per sq. mi.)             0
NATL_Coastline (coast/area ratio)           0
NATL_Net migration                          1
NATL_Infant mortality (per 1000 births)     1
NATL_GDP ($ per capita)                     0
NATL_Literacy (%)                           6
NATL_Phones (per 1000)                      1
NATL_Arable (%)                             0
NATL_Crops (%)                              0
NATL_Other (%)                              0
NATL_Climate                               18
NATL_Birthrate                              1
NATL_Deathrate                              2
NATL_Agriculture                            6
NATL_Industry                               7
NATL_Service                                7
AvgCigarettePriceDollars_Avg               73
AvgTaxesAsPctCigarettePrice_Avg            72
dtype: int64

In [ ]:
周洋